# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

workflows:
  version: 2
  run-tests-and-publish:
    jobs:
      - run-tests:
      - publish-github-page:
          requires:
            - run-tests

jobs:
  run-tests:
    working_directory: ~/saljuama.github.io
    branches:
      only:
        - dev
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  publish-github-page:
    working_directory: ~/saljuama.github.io
    branches:
      only:
        - dev
    steps:
      - checkout
      - run: yarn deploy
